API_HOST_URL: https://courses.madrasafree.com
ECOMMERCE_URL: https://courses.madrasafree.com
ENVIRONMENT_DISPLAY_NAME: Madrasa
PLATFORM_NAME: Madrasa
PLATFORM_DESTINATION_NAME: courses.madrasafree.com
FEEDBACK_EMAIL_ADDRESS: admin@madrasafree.com
OAUTH_CLIENT_ID: uMqVttUIoFg5q9tcwGyxm88tXBQb7bp1iYOJlAYd
APP_SHORTCUT_NAME: "מדרסה"
FAQ_URL: https://madrasafree.com/faq
DISCOVERY:
  COURSE:
    TYPE: 'native'
NEW_LOGISTRATION_ENABLED: False
USER_PROFILES_ENABLED: True
COURSE_VIDEOS_ENABLED: True
COURSE_DATES_ENABLED: False
WHATS_NEW_ENABLED:
DISCUSSIONS_ENABLED: True
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: True
VIDEO_TRANSCRIPT_ENABLED: True
PUSH_NOTIFICATIONS: True
YOUTUBE_PLAYER:
  ENABLED: True
  API_KEY: 'AIzaSyCWOv3pAdWI1FIc1H0T9gmnSpptuTEu9fI'
GOOGLE:
  ENABLED: true
  GOOGLE_PLUS_KEY: '679899712987-4rvsdoq6tlbosehi16st6giietfp2fjv.apps.googleusercontent.com'

FIREBASE:
  ENABLED: True
  ANALYTICS_SOURCE: 'firebase'
  CLOUD_MESSAGING_ENABLED: TRUE
  PROJECT_NUMBER: '840337900811'
  PROJECT_ID: 'madrasafreeapp'
  OAUTH_CLIENT_ID: '840337900811-05clio8hdk16tflsmkatisg7cg8e2dfl.apps.googleusercontent.com'
  CURRENT_KEY: 'AIzaSyAyegtPEceocCTfp7uien6LtFSeCGkjiMM'
  MOBILE_SDK_APP_ID: '1:840337900811:android:6d7e5b386fba7e9c444e0e'
